### ISSUE TITLE
Show "No Linter" instead of "No Issues" on files not being linted

### ISSUE THREAD

**Issue by UziTech** [steelbrain/linter#1137]
It would be nice to see "No Linter" or something like that in the status bar instead of falsely reporting "No Issues" when the current file grammer does not have a linter installed

**Comment by steelbrain** [comment]
This has been fixed in [`linter-ui-default`](https://github.com/steelbrain/linter-ui-default). The way we fixed this is by adding a status spinner at the bottom and showing the names of all linters being executed on a file.

The screenshot of it in action can be found in [`busy-signal`](https://github.com/steelbrain/busy-signal) repo.

To try the new UI before it's released, the instructions are in the repo README
