### ISSUE TITLE
Liner is not working 

### ISSUE THREAD

**Issue by erdemalpkaya** [steelbrain/linter#1140]
Hey everyone;

I download Atom Linter and also linter special language as well, but still not working! I tried hundred times, Do I have to download any special think that I couldn't see? Can you give me any recommended, please? I am using macbook pro. Thank you

**Comment by florianb** [comment]
Hi @erdemalpkaya, it is unlikely that the linter itself is not working. A lot of issues with the functionality of the linter belong to the specific language-plugins.

Which "linter-*"-packages do you try to use?

**Comment by erdemalpkaya** [comment]
Hey @florianb,  my main problem language is c program I used html and it was working.  Thank you for message

**Comment by florianb** [comment]
Hi @erdemalpkaya, then your issue should belong to https://github.com/AtomLinter/linter-clang, i'd like to ask you clossing this issue here and open a new one at linter-clang.

Please keep two things in mind:

1. linter-clang **can't** lint on the fly, therefore you must save a file before it gets linted.
2. there are already open issues, check first if your issue might belong to these.

**Comment by steelbrain** [comment]
Thanks @florianb, appreciate the help :+1: 
Closing based on discussion above

**Comment by florianb** [comment]
Thanks @steelbrain - you're welcome! 👍

**Comment by erdemalpkaya** [comment]
@florianb thank you for your  kindly recommends  I'm going to close this issue, I will check next time more carefully :) happy coding

**Comment by florianb** [comment]
@erdemalpkaya - you're welcome. If you're new to the linters it's sometimes not easy to make the first steps.. :)

**Comment by erdemalpkaya** [comment]
I'm new to make code and Atom and also my new computer which I started last week, imagine how hard for me :). See you next time with my new questions.  Have a good day
