### ISSUE TITLE
Lint errors should prevent save

### ISSUE THREAD

**Issue by domenkozar** [steelbrain/linter#1159]
I might be missing something, but when working with processes that reload,
it's really convenient for linter to catch errors and prevent reloading of the process
that will fail.

For example, working with [Elm](elm-lang.org) the linter catches all type
errors, but it doesn't prevent save so webpack-dev-server fails to compile and hangs.

@steelbrain is that reasonable?

**Comment by SpainTrain** [comment]
Sounds like an issue with the watch loop.  webpack-dev-server _should_ be able to gracefully handle failed compilation (it does in our project), so this seems like a build tools issue rather than linter issue.  There are resources for troubleshooting such issues (can share if helpful).

Prevent save on lint failure could be an interesting _option_, but IMO default behavior should be that when one presses `ctrl/cmd-s`, the file is saved to disk.  There are a number of situations during dev where linting fails but you still want to save your progress (e.g., having a bunch of library imports (some unused) while figuring out which methods you actually want to us to solve a particular problem).

**Comment by steelbrain** [comment]
@domenkozar The points @SpainTrain raised are very valid and I personally agree with them. Do you have any counter arguments?

**Comment by steelbrain** [comment]
Closing for the lack of response
