### ISSUE TITLE
severity 'info' should not count as an issue

### ISSUE THREAD

**Issue by FlorianObermayer** [steelbrain/linter#1183]
I'm currently developing a which shows not only errors and warnings but also information. Those messages flagged with severity 'info' should not be interpreted as an issue and thus should not be counted to the global "Issue" list:
![image](https://cloud.githubusercontent.com/assets/4497761/16085732/4baec79c-331d-11e6-8da4-2178e1ac0c69.png)

**Comment by steelbrain** [comment]
tbh linter was built to show errors and warnings and not info about the code

**Comment by FlorianObermayer** [comment]
I understand your point, but on the other hand what is the severity level 'info' serving for? Maybe there should be an Issue "filter mechanism" to select what kind of severities you want to have listed in your issue list. I think about something like the Error List from Visual Studio.

**Comment by Arcanemagus** [comment]
The definition of what "Info" means varies based on which linter is providing the message, _and_ who is interpreting the message. Linter doesn't, and in my opinion _shouldn't_ care about that as there is no way for it to qualify which "info" messages are ones the user cares about, and which are just information that the user can ignore.

The argument could be made that a linter shouldn't flag messages like that, but we don't live in that perfect world 😛. Maybe an option to not count them could work, but the default shouldn't be to ignore them there.

**Comment by sindresorhus** [comment]
I also think `info` messages shouldn't count towards the total issue count. If there's only one issue and it's a `info` message, I would change the bottom bar text to be blue and say `1 info` instead.

**Comment by wandel** [comment]
I'm creating a linter that runs unit-tests in the background, and I would like to be able to hide some messages types from the bottom panel & total count, but still have the gutter marker.

The reason why i would like this functionality is provide feedback to the user throughout the various stages (test collected/scheduled, test is running) as well as the final outcome. Some tests take a long time, and i would like to show the user that they have been scheduled/running, instead of just having the results show up some time in the future. Also I would like to show passing tests and not have them show up in the bottom panel/count.

I'm happy to put together a pull request if its something you would consider merging in.

**Comment by alygin** [comment]
I agree with the opinion that Linter shouldn't make decisions about showing or hiding issues based on their severities. But what Linter could do is to deliver the information about issues in a bit more digestible manner. I would advance @sindresorhus's idea and suggest the following enhancements:

 1. The issues counter must have the color of the most severe message. If there were errors, it must be red. If there were nothing more severe than warnings, it must be yellow. If there were only infos, it must be blue. If there were no issues, in must be green.
 2. If all the messages have the same severity, its must be used in the message. Otherwise, the word 'issue' comes to play. For instance, '3 errors', '2 warnings', '6 issues', 'No issues'.

In many cases it would help to get the issues overview at a glance, without necessity to go through the whole list searching for important information.

**Comment by rictic** [comment]
I agree with @alygin's proposal, save for the message. IMO `32 issues` in red isn't as useful if most of them are warnings or errors. I'd prefer the text of the message state only the number of the most severe type of issue.

**Comment by steelbrain** [comment]
Linter v2 is finally out people. You can read more about it in the [release post](http://steelbrain.me/2017/03/13/linter-v2-released.html).
