### ISSUE TITLE
Confusion with linter packages.

### ISSUE THREAD

**Issue by trusktr** [steelbrain/linter#1187]
Is "linter" by `atom-community` the linter package required for use with linter-* packages by AtomLinter? it's a little confusing because those packages are under two separate usernames in the atom package registry, and a third (this one, @steelbrain) on GitHub.

It would be nice to put all under a single username so people aren't confused and know they are installing a group of packages that are for certain meant to work with each other (and users won't wonder if they installed the correct packages, and won't wonder if there are other package from different users to install as alternatives for the same AtomLinter packages).

**Comment by trusktr** [comment]
Three usernames total (so far that I know of): AtomLinter, atom-community, and steelbrain.

**Comment by steelbrain** [comment]
Yeah well this is the life story

1. I wrote linter
2. Moved it to AtomLinter because they offered it, thought it would be a good idea
3. Turned out to be a terrible idea, they were forcing their ideas into the project, moved to `atom-community`
4. Moved back to my own username because got into an argument with a person who was an owner there and wanted to dictate the future of the project. For the better and more focused future, I moved it back to where it really belongs.
