### ISSUE TITLE
Request: Right-click to add warnings/errors to ignore list

### ISSUE THREAD

**Issue by xpol** [steelbrain/linter#1261]
As asked here: https://github.com/AtomLinter/linter-luacheck/issues/23.

I think it's nice to let linter have support for right click menu for warnings/errors, and notify linter-plugins when the menu item is cicked.

**Comment by steelbrain** [comment]
Hi @xpol, this has actually been fixed in a different way. See [`message.solutions` in Message v2](https://github.com/steelbrain/linter/blob/master/docs/types/linter-message-v2.md#type).

Also please note that this is the behavior of the unreleased linter v2, for linter v1 you'll have to use `fixes` (as found in wiki)
