### ISSUE TITLE
option to remove or delete a warning

### ISSUE THREAD

**Issue by tommygebru** [steelbrain/linter#1279]
option to remove or delete a warning from the list of errors, for example in html most of the errors for meta, link, and script tags... 
Users should have the option to dismiss these with a toggle button (x).

They take up too much screen real estate!!

**Comment by steelbrain** [comment]
Your request is very valid @tommygebru. But you should open the issue in the individual linter you are trying to disable the errors. While there is a way in Linter v1 to disable all warnings (`ignoredMessageTypes`) but it will disable all warnings on all file types.

Again, this package is the base linter, this request belongs to the individual linter provider

**Comment by tommygebru** [comment]
Ok that sounds pretty cool, but to disable all warnings would be impractical

**Comment by steelbrain** [comment]
Exactly, therefore you should open this bug in the linter provider who has power over the individual warnings so you can disable some without disabling all

**Comment by Arcanemagus** [comment]
Two things here:

* A button on each individual message to remove/hide it is needless complexity/clutter in my opinion, and would be meaningless as each new lint call would bring it right back... for most linters this would be every time you typed in the file.
* If your problem is that you have the Panel enabled and it is covering the entire screen then this is a bug and should be handled here, I thought this was fixed long ago though so you may want to check that your packages are up to date first.

**Comment by tommygebru** [comment]
Ok thank you I understand now, so I changed the replaced the linter
extension although in hindsight it would have been simpler to just follow
the directions and remove the warnings by actually complying to the
original linter extension
