### ISSUE TITLE
Noob aware suggestion

### ISSUE THREAD

**Issue by piejanssens** [steelbrain/linter#1292]
In Atom it would be good if the language of the file does not have a compatible linter installed that this is shown in the status bar instead of "No Issues".

**Comment by steelbrain** [comment]
That has actually been fixed in linter-ui-default, head over to it's README for installation instructions if you wanna use it before it's released to the general public (it's pretty stable).

The way we fixed this is by adding a status indicator on the bottom panel that spins when a linter is executing and shows the history of the last few linters executed on files.

**Comment by piejanssens** [comment]
Great stuff!
