### ISSUE TITLE
Messages v2 protocol ideas

### ISSUE THREAD

**Issue by fulldecent** [steelbrain/linter#1298]
Structured Acceptance Test is an open format that is very similar to the Messages v2 protocol.

https://github.com/fulldecent/structured-acceptance-test

To promote interoperability between all linters / acceptance tests processes in the world, it would be nice if the messages v2 protocol and STAT format were harmonized. Note: STAT format is already harmonized (one-to-one compatible) with Code Climate's SPEC format.

Already I see Messages v2 adds `fixes`, an awesome feature.

This issue makes other comparisons in an effort to promote one-to-one compatibility between STAT and Messages v2.

-----

Following are ways that Messages v2 are different than STAT and rationality for updating it to match STAT:

 - (From messages v1.) `Trace` includes a `severity` -- recommendation: remove this -- if a backtrace references other code then that other code is assumed valid therefore the other referenced code should not be classified as *error*, *warning* or *info*.

Here are new features that Messages v2 (and Standard Linter v2) can consider adding which STAT already has.

 - STANDARD LINTER v2. Linter documentation of *repeatability*. Some linting processes may be able to specify that their results are guaranteed not to change under certain circumstances. The consumer (Atom) could use this information to great benefit by not repeating a lint operation if it knows that results will be the same. Here are three categories of repeatability with examples:
   - **Volatile** -- *Linter that checks if today's date is in the target file*. This test must be rerun constantly, Atom should rerun the linter every time you edit or open the file. **This is the weakest guarantee and should be default. (Or you can make specifying repeatability required to avoid implicit default.)**
   - **Repeatable** -- *Linter compiles c code*. If the code compiled yesterday, you can be sure it will compile again today (assuming same compiler and compiler settings are used.) But if file `a` is edited then all other files must be rechecked.
   - **Associative** -- *Linter that greps for swear words*. If file `a` is edited then there is not need to rerun the linter for file `b`. **This is the strongest guarantee that a linter can make.**

 - MESSAGE v2. Time to fix. An estimated time, in seconds, that a human would need to correct this problem. Some producers like to make this estimate, so STAT allows it in the data format.
 - MESSAGE v2. Category. Code Climate defined several categories of issues. STAT includes them and provides documentation for these categories.
 - MESSAGE v2. `solution` without replacement text or process. It may be desirable to list recommendations using imperative language even if you are not able to provide an exact fix.
   - **Problem message (you already have this)** -- this explains what the problem is. *Warning: swear words are not allowed in this document.* 
   - **Fix with replacement text (you already have this)** -- this is clickable and uses imperative wording. *Replace `s**t` with `poop`.*
   - **Fix without replacement text (proposed new feature)** -- this tells you what to do using imperative language but does not have a recommended clickable replacement. *Reword this sentence to make it more classy.*
 - MESSAGE v2. A message without a file range. It may be possible that a message applies to an entire file but no specific place in the file. *This file is named .cxx but your style guide requires this to be named .cpp.* Most findings from https://github.com/AtomLinter/linter-flint fall in this class.

**Comment by fulldecent** [comment]
Here is the main motivation of this issue: https://github.com/fulldecent/structured-acceptance-test/issues/17

We want to use standardized output for all linters. Then we'll have a boilerplate adapter from this standardized format to Atom Linter (this project). Then there will be an explosion in the number of linters that work with Atom.

**Comment by Arcanemagus** [comment]
> (From messages v1.) Trace includes a severity -- recommendation: remove this -- if a backtrace references other code then that other code is assumed valid therefore the other referenced code should not be classified as error, warning or info.

Messages v1 is no longer being worked on, all changes are being made in v2. Even if it was being changed, what you are saying makes no sense anyway. The fact that the referenced code is valid (or not) has nothing to do with the fact that it is a reference for the invalid code that triggered the message in the first place.

----

> STANDARD LINTER v2. Linter documentation of repeatability.

This is interesting, but unfortunately has no bearing on how this architecture works. The linter providers are running external programs, with the only input coming from Atom being whether the file has changed or not.
  * Volatile: Virtually all providers fall under this category as if the file has changed it needs to be re-checked to see if past issues have been fixed or new ones have been introduced.
  * Repeatable and Associative: These are the same thing, and are handled by the `scope` attribute of a provider. If a provider marks itself as `scope: 'file'` then these attributes have no bearing on it since it only deals with a single file at a time. If however it marks itself as `scope: 'project'` then it is both _not_ Repeatable, and _not_ associative since it can / will return results for multiple files and any of them may change.

> MESSAGE v2. Time to fix.

An interesting idea, no linter that I have seen provides this information so it was never added to the spec but there is nothing against adding it.

> MESSAGE v2. Category.

It would have been helpful to have linked to [Category](https://github.com/fulldecent/structured-acceptance-test/blob/master/Stat-Output.md#category) in the specification here 😛. Although the idea behind this is nice, none of the base linters provide information like this, so it would be up to the providers to maintain a mapping list where possible. This is quite a bit of extra work to maintain for what seems like little benefit. Most messages don't really fit into these categories though, so at best this would have to be optional.

> MESSAGE v2. solution without replacement text or process.

This can already be implemented with the function method, which allows the provider to do whatever it requires when the "fix" is triggered, including messaging the user in some manner. I would argue that your proposed example better fits into the `description` attribute though.

> MESSAGE v2. A message without a file range.

This was actually in messages v1, but was removed due to the extra complexity involved with handling it and the lack of use. Currently the idea is to simply mark the entire first line of a file as the "location" of messages like this. This may require revisiting though as pure project scoped messages that have no file associated with them aren't currently allowed.

**Comment by fulldecent** [comment]
Thank you for all this review. Here are couple open items.

> Repeatability

Thank you, I see how scopes works in `linter` already and this looks great. The only novel idea from STAT perhaps is to add a `repeatable?` attribute to Standard Linter v2. This would signify that a `file` or `project` scope run through the linter twice is guaranteed to produce identical output.

For a compiler this will be `false` because you may install a missing library and that fixes a compiler error so running it again will work now. For a spelling checker this will be `true`.

The benefit of specifying repeatability is that when you do Edit -> Undo, then Atom can reuse linter results from the last run. Linting can be expensive, that is why I'm caring about this.

> [Category](https://github.com/fulldecent/structured-acceptance-test/blob/master/Stat-Output.md#category)

Yes, definitely optional. Personally I don't think it's the most useful, but since Code Climate uses it, we adopted it in STAT. 

> Project scoped messages

Imagine checking out an old commit on a project. Then a linter retrieves output from the CI/build server (like Travis). There will be lots of useful test artifacts like unit test results that you might want to view in Atom, which are project scoped.

---

Thanks for all your feedback, studying `linter` has been very helpful for me in learning about static analysis.

**Comment by steelbrain** [comment]
Just a side note that the case where Atom would reuse linter results from the last run is about 1 in a million and not really worth adding special cases for. I'll add my brief response soon

**Comment by Arcanemagus** [comment]
> Repeatability

Ah, you don't mean repeatable at the level of the file then but the actual contents. So a file with `abcdef` will always return the same results, regardless of what other files on the system have changed?

If that's the case it will be _extremeley_ rare that that could be set to true unless the linter the provider wrapped used a hardcoded list and was never updated. I don't think any _useful_ provider would be able to rightfully set that to true since even your example of a spell checker can change if the software running the check updated to say fix a bug, or the dictionary it was using was updated to include different words.

> Project scoped messages

That example doesn't really fit with what linters are meant for, but more of a [build system](https://atom.io/packages/build) level thing. Linters are meant to check the current status of a file / project and report on that status. Checking out an older commit would just mean running the lint process against that version.

**Comment by fulldecent** [comment]
If repeatability is specified, two common cases can avoid relinting:

 1. Undo -- Cached lint results can be reused.
 2. Opening a file -- You saved the file yesterday and opened it today. Bam, the lint results are immediately available.

Sorry, I should have explained # 2 earlier since that is the most common and useful case here. FYI, if the dictionary linter is upgraded to a new version then all guarantees of repeatability are invalidated (i.e. the cache is flushed).

**Comment by steelbrain** [comment]
Whelp, v2 just got published. Thank you for the discussion @fulldecent!

Closing as meta, but feel free to continue discussing
