### ISSUE TITLE
Bad view multiline errors. ver 2.0.

### ISSUE THREAD

**Issue by Toxblh** [steelbrain/linter#1352]
Multiline error view, how inline. And read very bad.

<img width="1587" alt="screen shot 2017-03-14 at 12 37 19" src="https://cloud.githubusercontent.com/assets/2198153/23894428/1b3f3814-08b3-11e7-9866-8f9f7e5e2793.png">

**Comment by steelbrain** [comment]
Hi @Toxblh 

That is actually not a multiline error, or it would've been shown in multiple lines, can you provide some repros steps please?

**Comment by Toxblh** [comment]
Ok, this error in terminal view:
<img width="726" alt="screen shot 2017-03-14 at 12 41 58" src="https://cloud.githubusercontent.com/assets/2198153/23894557/a8c0b50a-08b3-11e7-9e29-fa07d6470f1d.png">

and ver 1.0 correctly viewed errors, in multiline

**Comment by steelbrain** [comment]
I see, what's your Linter Provider? It could be the culprit here

**Comment by Toxblh** [comment]
<img width="528" alt="screen shot 2017-03-14 at 12 44 08" src="https://cloud.githubusercontent.com/assets/2198153/23894653/05419c7c-08b4-11e7-856d-cf2da746c4b7.png">

**Comment by steelbrain** [comment]
Can you invoke the `linter:debug` command in the file path where you have the error and post the resulting notification please?

**Comment by steelbrain** [comment]
Thank You, will investigate

**Comment by Toxblh** [comment]
Ok

**Comment by Toxblh** [comment]
My packages, maybe this help you:
atom-beautify
atom-clock
atom-ternjs
autocomplete-modules
docblockr
editorconfig
file-icons
git-blame
git-time-machine
highlight-line
highlight-selected
language-babel
linter
linter-eslint
linter-stylelint
merge-conflicts
multi-cursor
pigments
rester
script
sort-lines
Stylus
svg-preview
svgo
toggle-quotes

**Comment by caesarsol** [comment]
Hello, having this issue as well, it seems to be related to eslint `parsing error`s only:

<img width="1053" alt="screen shot 2017-03-14 at 12 48 37 pm" src="https://cloud.githubusercontent.com/assets/1799710/23899423/5ab9a45a-08b5-11e7-9c20-70c888d8712e.png">

### Manual eslint run

```bash
$ node node_modules/eslint/bin/eslint.js --cache --cache-location=/tmp/ src/

/Users/caesarsol/dev/project/file.js
  102:32  error  Parsing error: Unexpected token

  100 |     },
  101 |
> 102 |     get eventGroupsVisible() {;:;
      |                                ^
  103 |       const fromTs = this.eventsTimeExtent.max - (config.intervalToShow + config.intervalToFetch * 2)
  104 |       const toTs = this.eventsTimeExtent.max - 1
  105 |       const eventsGrouped = this.getEventsFromTo(fromTs, toTs)

✖ 1 problem (1 error, 0 warnings)
```

### Linter debug (stripped)

Platform: darwin
Atom Version: 1.15.0
Linter Version: 2.0.0
All Linter Providers: 
  - ESLint
Matching Linter Providers: 
  - ESLint
Disabled Linter Providers; 

### Other useful info

linter-eslint version: 8.1.3
Hours since last Atom restart: 0.1
Using local project ESLint from: /Users/caesarsol/dev/project/node_modules/eslint

Hope these info were useful.
Thanks for your work on this project!

**Comment by Arcanemagus** [comment]
Very interesting, `linter-eslint` doesn't actually output multiline messages, since it's only designed to output short messages. It _should_ have only been grabbing the `102:32  error  Parsing error: Unexpected token` part, but seems to be grabbing more now, possibly due to a change in the output from ESLint. Can you file an issue over there for this?

**Comment by caesarsol** [comment]
I don't think eslint has changed, I'm using the same version.

Maybe linter-eslint was only displaying the first line in the popup, and now is displaying all of it?

In the lower bar I'm sure multiline messages were allowed before as they are now.
