### ISSUE TITLE
Hide UI when there are no issues

### ISSUE THREAD

**Issue by janneraiskila** [steelbrain/linter#1357]
The three zeros and the green dot should be hidden when nothing is going on. These cause a lot of unnecessary clutter in the UI and don't serve a useful purpose when there are no issues/errors/activity.

**Comment by steelbrain** [comment]
Hi @janneraiskila 

Thanks for the report!
I'm going to fix this in two different ways

- [Fix the shifting around of indicator](https://github.com/steelbrain/linter/issues/1356)
- [Add an option to hide that that bottom status bar](https://github.com/steelbrain/linter-ui-default/issues/181)

I cannot do the hide when no errors part because that would make the UI shift around a lot, but I hope that first one will be enough to make the UI comfortable for you.

Thanks again for the report! Please go subscribe the issues linked
