### ISSUE TITLE
Settings options not working

### ISSUE THREAD

**Issue by ithuvanian** [steelbrain/linter#1363]
After the update to version 2, it seems the options in the settings (gutter enabled, error panel, error inline, underlines) are impossible to turn off... when I uncheck the corresponding boxes, the underlines, tooltips, etc continue to appear.
Atom version 1.15.0 (latest version) on Ubuntu 16.04
Thanks

![screen](https://cloud.githubusercontent.com/assets/16740960/23929686/322a9ef6-08fe-11e7-98e9-49762b30e8f0.png)

**Comment by steelbrain** [comment]
Hi @ithuvanian 

It's an Atom bug you're experiencing, it's showing you configs that we have already removed, please configure UI settings in `linter-ui-default` instead of `linter`.

and if you wanna get rid of the outdated configuration, I don't know any way other than `mv ~/.atom/config.cson ~/.atom/config.cson.bak`
