### ISSUE TITLE
question: How to remove the "Welcome to linter v2" dialog

### ISSUE THREAD

**Issue by zer09** [steelbrain/linter#1398]
Sorry, I am new to atom.io I just want to remove the welcome screen.
![linter](https://cloud.githubusercontent.com/assets/780780/24301279/2dc27dcc-10ea-11e7-9081-d1d46be38817.png)

Thanks

**Comment by steelbrain** [comment]
Hi @zer09, you should be getting that dialog only once, and only if you have used linter v1 on that computer. Are you getting this on every reboot?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: zer09 <notifications@github.com> Date: 3/24/17  8:33 PM  (GMT+05:00) To: steelbrain/linter <linter@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [steelbrain/linter] question: How to remove the "Welcome to linter v2" dialog (#1398) 
Sorry, I am new to atom.io I just want to remove the welcome screen.


Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steelbrain/linter","title":"steelbrain/linter","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/steelbrain/linter"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"question: How to remove the \"Welcome to linter v2\" dialog (#1398)"}],"action":{"name":"View Issue","url":"https://github.com/steelbrain/linter/issues/1398"}}}

**Comment by zer09** [comment]
Yes I'am getting this on every reboot. I can see on the package manager it is v1.2.1.
![linter](https://cloud.githubusercontent.com/assets/780780/24317851/7cc87fa0-1137-11e7-83e7-2d15f4176a24.png)

**Comment by steelbrain** [comment]
Can you try reinstalling to see if it fixes the issue for you?

```
apm uninstall linter
apm install linter
```

**Comment by zer09** [comment]
Sorry, but it still showing up. I also tried it reinstall using the package manager.
actually it was installed with the proton-mode pacakage.

**Comment by steelbrain** [comment]
@Arcanemagus Are you able to repro this? I am not

**Comment by zer09** [comment]
I will reinstall atom later and install linter first before proton-mode.

**Comment by zer09** [comment]
Ohh I did a fresh install of the atom install the linter and its working fine it is not showing the welcome screen anymore, but after installing the proton-mode, the problem came back.

To repro:
I did fresh install of the atom.
Install the linter using apm, then it is working fine(restart the atom several times and all is good).
install the proton-mode using apm, after installing open the atom then the proton-mode install its dependencies.
then the problem came back.(restart several times but the problem persist).

**Comment by steelbrain** [comment]
The way linter determines to show if v2 message is necessary, it **checks existence** of any of the configurations present in v1, if they exist it shows v2 welcome message and unsets those configs

The reason you might be having it again and again is because some package might be setting those configurations in itself, as to configure Linter for their own userbase. The problem can be fixed by not setting that config from the guilty package.

As discussed, this is not a problem with linter itself so closing but feel free to continue discussing

**Comment by aculich** [comment]
I also experience the repeated popups, not just when starting atom, but every time I open a new window.

I'd like to request that you consider re-opening this issue to either add a way to permanently suppress the message or to provide sufficient detail in the popup message to identify which settings/packages are triggering it every time.

Thanks!

**Comment by steelbrain** [comment]
Hi  @aculich 

We actually have the solution permanently fixed within our own package, but unfortunately, we can't control other packages interfering :)

**Comment by zer09** [comment]
@aculich 

Try disabling all community packages, then enable it one-by-one to find what package causing the problem. Because that what I  did to find what packages causing it. 😄
