### ISSUE TITLE
Markdown or HTML in the excerpt?

### ISSUE THREAD

**Issue by Gert-dev** [steelbrain/linter#1407]
Hello

I'm trying to migrate to version 2 of the linter for PHP integrator. Up until now I had been using the v1 indie linter and [was able to push HTML in my messages](https://php-integrator.github.io/images/linting.png). However, this now seems to be restricted to the actual description of the message and the HTML is instead escaped. Is there a specific reason for this limitation (perhaps to prevent linters from going wild with formatting)?

I've considered removing the markdown from my messages entirely, but, as visible in the screenshot, it better delimits code or other interesting parts of the message. (Either markdown and HTML would do fine for my use case, I receive the former but can easily convert to the latter.)

Thanks in advance

**Comment by steelbrain** [comment]
Hi @Gert-dev 

As for the reason, I decided to switch to markdown because a lot of people were adding ribbons and links in the html, and were not painting them with appropriate classes and it would look ugly for the end users, now they can all just use markdown links and the parser automatically adds classes to the input.

You and @lierdakil have both requested this so I am thinking of a graceful way to handle both the markdown and html

**Comment by Gert-dev** [comment]
Thanks for considering this. However, I want to clarify that I don't explicitly require HTML in my messages anymore as I have recently switched to providing the messages in markdown format (all I needed was some bold text and PHP documentation is already suggested to be markdown, so it seemed natural to use it here as well).

I merely mentioned it because I can also convert my markdown to HTML, if that is more convenient for you. I'm mostly looking for a way to add a bit of markup to the messages that the user sees without having to let them click then open :-).

**Comment by steelbrain** [comment]
Oh right, shouldn't handle issue reports when dehydrated 😛 

I fear people are going to abuse it, by adding links and ribbons and stuff haha. Keeping excerpt plain text was one way to enforce consistency in the basic messages you see from all linter providers. For example, ESLint, and others used to include a link to the relevant rule on the web, since `url` is a separate property you can provide in v2, it was still going to keep using a ribbon most likely had the excerpt not been text-only.

I think a good workaround for you would be to wrap the `duplicate` to make it `"duplicate"`, maybe?

**Comment by lierdakil** [comment]
A small addition: I don't actually *require HTML*. I still think that Markdown was never intended for programmatic generation, so it's a *really* awkward choice, but again, your project, you're the king. FWIW, I would argue that accepting HTML and sanitizing/transforming it with something like [cheerio](https://github.com/cheeriojs/cheerio) would be much more straightforward (also Markdown generally accepts some HTML stuffs, so yeah...)

What kills this idea for me is significant whitespace in Markdown though. My use-case has significant whitespace of its own, and the two don't mix well (also my yse-case, i.e. Haskell compiler, occasionally uses backticks in its output, so that's a bit of a problem as well). Having an option to pass plaintext which would be displayed with `style="white-space: pre-wrap;"` could be a direct solution to my problem. Of course, if arbitrary HTML was accepted, I could do that myself.

**Comment by Gert-dev** [comment]
@steelbrain Perhaps you are right, I'll try replacing it with quotes. It doesn't look as neat as the bold text, but perhaps that is also a good reason to keep the messages more concise.

Feel free to close this if you want :-).

**Comment by steelbrain** [comment]
Hi @lierdakil

I would personally not use the word `king` for myself, I try to be democratic here. The thing that you learn the hard way maintaining a project with such a diverse user base is that you cannot please everyone. With that being said, the `description`s are rather long compared to excerpts and thus were never meant for programmatic generation. It was meant to be fetched from some docs repository and stripped out and rendered.

There's definitely a usecase where you want to preserve whitespace in your description. You don't necessarily need HTML for that, for example you can just do this in description
```js
{
  // ... other props ...
  description: `<pre class="my-linter-preserve-format">Insert\n pre\n formatted\n text\n here</pre>`,
}
```
and then you can add this to your package stylesheet
```css
.my-linter--preserve-format {
  /* override background inherit of <pre> md tag */
  background: inherit;
}
```

Glad you agree on the quotes @Gert-dev
