### ISSUE TITLE
Error Running Unknown

### ISSUE THREAD

**Issue by JLCCI** [steelbrain/linter#1418]
Linter spans those messages every 7-8 minutes, works OK otherwise. Reported it before but the latest version did not fix it. Thank you.

![screenshot from 2017-04-05 15-47-16](https://cloud.githubusercontent.com/assets/18163728/24693160/3fe68c42-1a17-11e7-844a-1cddce7c938e.png)

**Comment by steelbrain** [comment]
Hi @JLCCI 

We can't really fix that specific one, because for v1 we cannot enforce the name requirement for backward compatibility reasons and we can't predict it either. Anyway the package seems to be loading fine, executing throws errors and you can easily guess the name of the package by looking at the dev tools stack

**Comment by JLCCI** [comment]
Ahh I see, I will report it to the appropriate package.
