### ISSUE TITLE
Show old output until new output is ready

### ISSUE THREAD

**Issue by i-am-the-slime** [steelbrain/linter#1457]
I am using this in conjunction with a Scala compiler. This language is very slow to compile so, I fix one error, hit save to trigger a recompile. Unfortunately right at the same point in time, the previous output is removed. It would be nice if it didn't get removed immediately but replaced with the new errors when they are ready.

**Comment by Arcanemagus** [comment]
That's how things already work: Linter only updates messages when a provider gives it results.

The only other way that the text could be losing its marker is if it is modified enough that Atom no longer considers the marker valid and automatically removes it. Do you have external tools running during build that are re-writing the files? There is a bug in Atom where occasionally it replaces the entire file instead of only the differences when the file is updated outside Atom.

**Comment by i-am-the-slime** [comment]
I don't think any tools do write operations to the file. Maybe the provider is at fault here? https://github.com/inkytonik/atom-sbt this is the one.

**Comment by Arcanemagus** [comment]
Looks like that provider is using the "Indie" API, which means it controls when messages are updated.

It only does so in two places: [here](https://github.com/inkytonik/atom-sbt/blob/v0.10.0/lib/project.coffee#L136) and [here](https://github.com/inkytonik/atom-sbt/blob/v0.10.0/lib/project.coffee#L168). If those two cases don't look like they are causing this you should file an issue on that provider.

**Comment by i-am-the-slime** [comment]
Okay, cool I will try to take it in the provider, thanks a lot!
