### ISSUE TITLE
Clicking the Linter window makes the text disappear

### ISSUE THREAD

**Issue by Cole128** [steelbrain/linter#1473]
Linter works fine while I'm working, until I click it, to try and go to a line that has an error on it. Then it goes gray and I have to make it go down and come up again to fix it. I am using flake8 for python as my linter. Linter will also expand across the bottom of my screen when I click it, pushing a bar I have on the right side out of the way. I'm on the newest version of Atom and macOS.

Before:
![screen shot 2017-05-24 at 5 46 46 pm](https://cloud.githubusercontent.com/assets/25111343/26427129/713b8f96-40a9-11e7-9510-56c09cbd01e0.png)

After:
![screen shot 2017-05-24 at 5 46 56 pm](https://cloud.githubusercontent.com/assets/25111343/26427160/972cf1f4-40a9-11e7-8374-4fb5fff6e38f.png)

**Comment by Arcanemagus** [comment]
My guess is whatever package is providing that bar is breaking with the new Docks, especially since the "missing" sections sum up to the width of the bar that has disappeared.

That wouldn't happen to be Synced Sidebar would it? That's known to be broken with Atom v1.17.0.

If after disabling whatever that bar package is you still see this, please file an issue on [linter-ui-default](https://github.com/steelbrain/linter-ui-default) as this package itself has nothing to do with the UI.
