### ISSUE TITLE
Linter holds file locks, even after file is closed on Windows 10

### ISSUE THREAD

**Issue by itspomf** [steelbrain/linter#1582]
### Versions

`atom --version`

```
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

* linter:  2.2.0
* linter-eslint:  8.4.1

Windows 10 Enterprise 1709 (16299.431)

### Description

It appears that the linter / linter-eslint packages (not sure which) are holding file locks even after the file has been closed in Atom.  This results in Permission Denied errors when other processes attempt to modify the file (such as git).

### How to reproduce

1. Edit some javascript files in Atom with the linter enabled
2. Close the files
3. `git checkout -- .` to wipe your changes

This causes the following output, with one line per affected file:

```
error: unable to create file [REDACTED]: Permission denied
error: unable to create file [REDACTED]: Permission denied
error: unable to create file [REDACTED]: Permission denied
```

The permissions issue occurs until Atom is closed, presumably unloading the linter child process and releasing the locks.  If the linter is *not* running, no error occurs.

**Comment by Arcanemagus** [comment]
`linter` does nothing with files, the providers (`linter-eslint`) are what actually work with the files.

That being said I _highly_ doubt that `linter-eslint` is the real culprit here unless you are using some plugin for ESLint that is holding the file open.

I'm closing this since it has absolutely nothing to do with `linter`, if you disable `linter-eslint` and the behavior stops file an issue there and we'll try to debug it further.
