### ISSUE TITLE
when i run code. make error

### ISSUE THREAD

**Issue by Ibodwe** [steelbrain/linter#1587]
'python'��(��) ���� �Ǵ� �ܺ� ���, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.

**Comment by Arcanemagus** [comment]
If I had to guess, you probably don't have Python installed on your system. Without the proper encoding on that, or _any_ other details though it's impossible to say any more.

If you are having an issue getting a specific `linter-*` provider working please file an issue there. I'm going to close this issue since:
* We have no information to go off of
* It's impossible to be a `linter` issue anyway since `linter` doesn't need Python

Thanks for taking the time to file an issue!
