### ISSUE TITLE
Does not work with RAML files

### ISSUE THREAD

**Issue by pff729** [steelbrain/linter#1610]
Since updating to 2.3.0, linting in .raml files with api-workbench does not work. It doesn't show the errors. Had to downgrade to 2.2.0, it works fine there.

**Comment by Arcanemagus** [comment]
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. It's likely that the provider you are using is no longer supported by the current version of `linter`.

To get your provider (`api-workbench`?) working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use your provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.

You should forward the above message to the author of the provider as an issue so they know they need to update it.
